/**
 * ClawMark Extension — Build Configuration
 *
 * Auto-generated by scripts/build.sh — do not edit manually.
 * Environment: test
 * Built: 2026-03-04T19:11:39Z
 */

'use strict';

const ClawMarkConfig = {
    DEFAULT_SERVER: 'https://jessie.coco.site/clawmark',
    DASHBOARD_URL: 'https://jessie.coco.site/clawmark-dashboard/',
    ENV: 'test',
};

if (typeof Object.freeze === 'function') Object.freeze(ClawMarkConfig);
