/**
 * ClawMark — PR Creator (#86)
 *
 * Creates branches, applies fixes, runs validation (lint + type check),
 * and submits GitLab merge requests with error description and fix rationale.
 */

'use strict';

const { execFile } = require('child_process');
const https = require('https');
const http = require('http');
const { URL } = require('url');

const GIT_TIMEOUT = 30000; // 30s
const API_TIMEOUT = 15000; // 15s

/**
 * Generate branch name from issue metadata.
 *
 * @param {string|number} issueId - GitLab issue IID
 * @param {string} message - Error message (used for short description)
 * @returns {string} Branch name: autofix/<issue-id>-<short-desc>
 */
function generateBranchName(issueId, message) {
    const shortDesc = (message || 'error')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 40);
    return `autofix/${issueId}-${shortDesc}`;
}

/**
 * Create a git branch, apply fix, commit, and push.
 *
 * @param {object} params
 * @param {string} params.repoRoot - Git repo root
 * @param {string} params.branchName - Branch to create
 * @param {string} params.baseBranch - Base branch (e.g., 'develop')
 * @param {object} params.fix - Fix object from fix-generator
 * @param {object} params.errorEvent - The perception event
 * @param {object} [params.blameResult] - Blame analysis result
 * @param {Function} [params.execFn] - Override for exec (testing)
 * @returns {Promise<{ success: boolean, error?: string }>}
 */
async function createBranchAndCommit(params) {
    const { repoRoot, branchName, baseBranch = 'develop', fix, errorEvent, blameResult, execFn } = params;
    const exec = execFn || execFilePromise;

    try {
        // Fetch latest
        await exec('git', ['fetch', 'origin', baseBranch], { cwd: repoRoot, timeout: GIT_TIMEOUT });

        // Create branch from base
        await exec('git', ['checkout', '-b', branchName, `origin/${baseBranch}`], { cwd: repoRoot, timeout: GIT_TIMEOUT });

        // Apply fix files — use fix-generator's applyFix
        const { applyFix } = require('./fix-generator');
        const result = applyFix(fix, repoRoot);

        if (result.applied.length === 0) {
            return { success: false, error: `No files applied: ${result.failed.join('; ')}` };
        }

        // Stage changed files
        await exec('git', ['add', ...result.applied], { cwd: repoRoot, timeout: GIT_TIMEOUT });

        // Commit
        const commitMsg = buildCommitMessage(errorEvent, fix, blameResult);
        await exec('git', ['commit', '-m', commitMsg], { cwd: repoRoot, timeout: GIT_TIMEOUT });

        // Push
        await exec('git', ['push', '-u', 'origin', branchName], { cwd: repoRoot, timeout: GIT_TIMEOUT });

        return { success: true, applied: result.applied, failed: result.failed };
    } catch (err) {
        return { success: false, error: err.message };
    }
}

/**
 * Build a commit message for the auto-fix.
 */
function buildCommitMessage(errorEvent, fix, blameResult) {
    const typeLabel = errorEvent.type === 'js-error' ? 'JS' : errorEvent.type || 'error';
    const shortMsg = (errorEvent.message || 'unknown error').slice(0, 60);

    const lines = [
        `fix: [AutoFix][${typeLabel}] ${shortMsg}`,
        '',
        fix.description || 'Auto-generated fix from error analysis.',
        '',
    ];

    if (blameResult && blameResult.sourceFile) {
        lines.push(`Source: ${blameResult.sourceFile}:${blameResult.errorLine}`);
    }

    lines.push('', 'Auto-generated by ClawMark Auto-Fix Pipeline (#86)');

    return lines.join('\n');
}

/**
 * Run basic validation: lint + test on the repo.
 *
 * @param {string} repoRoot
 * @param {object} [opts]
 * @param {Function} [opts.execFn]
 * @param {string[]} [opts.commands] - Validation commands to run
 * @returns {Promise<{ passed: boolean, results: Array<{ cmd, ok, output }> }>}
 */
async function runValidation(repoRoot, opts = {}) {
    const exec = opts.execFn || execFilePromise;
    const commands = opts.commands || [
        { cmd: 'node', args: ['--check', '.'], label: 'syntax-check' },
    ];

    const results = [];
    let allPassed = true;

    for (const { cmd, args, label } of commands) {
        try {
            const output = await exec(cmd, args, { cwd: repoRoot, timeout: 60000 });
            results.push({ cmd: label || cmd, ok: true, output: (output || '').slice(0, 500) });
        } catch (err) {
            results.push({ cmd: label || cmd, ok: false, output: (err.message || '').slice(0, 500) });
            allPassed = false;
        }
    }

    return { passed: allPassed, results };
}

/**
 * Create a GitLab merge request.
 *
 * @param {object} params
 * @param {string} params.token - GitLab PAT
 * @param {string} params.project_id - Project ID or path
 * @param {string} params.source_branch - Fix branch
 * @param {string} params.target_branch - Target branch (e.g., 'develop')
 * @param {string} params.title - MR title
 * @param {string} params.description - MR description markdown
 * @param {string[]} [params.labels] - MR labels
 * @param {number[]} [params.assignee_ids] - Assignee user IDs
 * @param {number} [params.reviewer_ids] - Reviewer user IDs
 * @param {boolean} [params.draft] - Create as draft MR
 * @param {string} [params.base_url] - GitLab URL
 * @returns {Promise<{ iid: number, url: string }>}
 */
async function createMergeRequest(params) {
    const {
        token, project_id, source_branch, target_branch = 'develop',
        title, description, labels = [], assignee_ids = [], reviewer_ids = [],
        draft = false, base_url = 'https://gitlab.com',
    } = params;

    const encodedProject = encodeURIComponent(project_id);
    const data = {
        source_branch,
        target_branch,
        title: draft ? `Draft: ${title}` : title,
        description,
        labels: labels.join(','),
        remove_source_branch: true,
    };
    if (assignee_ids.length > 0) data.assignee_ids = assignee_ids;
    if (reviewer_ids.length > 0) data.reviewer_ids = reviewer_ids;

    const result = await gitlabApi('POST', `/api/v4/projects/${encodedProject}/merge_requests`, data, { token, base_url });
    return { iid: result.iid, url: result.web_url };
}

/**
 * Build the MR description from fix analysis.
 */
function buildMrDescription(errorEvent, fixResult, blameResult, issue) {
    const lines = [];

    lines.push('## Auto-Fix Summary');
    lines.push('');
    lines.push(`**Confidence:** ${(fixResult.confidence * 100).toFixed(0)}%${fixResult.isDraft ? ' (Draft — needs human review)' : ''}`);
    lines.push('');

    lines.push('## Error Details');
    lines.push('');
    lines.push(`| Field | Value |`);
    lines.push(`|-------|-------|`);
    lines.push(`| **Type** | \`${errorEvent.type}\` |`);
    lines.push(`| **Severity** | \`${errorEvent.severity}\` |`);
    lines.push(`| **Message** | ${(errorEvent.message || '').slice(0, 200)} |`);
    lines.push(`| **URL** | ${errorEvent.url || 'N/A'} |`);
    if (issue) {
        lines.push(`| **Issue** | #${issue.gitlab_issue_id} |`);
        lines.push(`| **Occurrences** | ${issue.count} |`);
    }
    lines.push('');

    lines.push('## Root Cause Analysis');
    lines.push('');
    lines.push(fixResult.analysis);
    lines.push('');

    if (blameResult && blameResult.sourceFile) {
        lines.push('## Source');
        lines.push('');
        lines.push(`File: \`${blameResult.sourceFile}\` (line ${blameResult.errorLine})`);
        if (blameResult.recentChanges && blameResult.recentChanges.length > 0) {
            lines.push('');
            lines.push('Recent changes:');
            for (const c of blameResult.recentChanges.slice(0, 3)) {
                lines.push(`- \`${c.hash?.slice(0, 7)}\` ${c.author}: ${c.message}`);
            }
        }
        lines.push('');
    }

    if (fixResult.fix) {
        lines.push('## Fix Description');
        lines.push('');
        lines.push(fixResult.fix.description);
        lines.push('');

        lines.push('### Changed Files');
        lines.push('');
        for (const f of fixResult.fix.files) {
            lines.push(`- \`${f.path}\``);
        }
        lines.push('');

        if (fixResult.fix.test_plan) {
            lines.push('## Test Plan');
            lines.push('');
            lines.push(fixResult.fix.test_plan);
            lines.push('');
        }
    }

    if (fixResult.risks && fixResult.risks !== 'none') {
        lines.push('## Risks');
        lines.push('');
        lines.push(fixResult.risks);
        lines.push('');
    }

    if (fixResult.alternative) {
        lines.push('## Alternative Approach');
        lines.push('');
        lines.push(fixResult.alternative);
        lines.push('');
    }

    if (issue && issue.gitlab_issue_url) {
        lines.push('## Related');
        lines.push('');
        lines.push(`Closes #${issue.gitlab_issue_id}`);
        lines.push('');
    }

    lines.push('---');
    lines.push('*Auto-generated by ClawMark Auto-Fix Pipeline (#86)*');

    return lines.join('\n');
}

/**
 * Clean up: delete branch and checkout base.
 */
async function cleanup(repoRoot, branchName, baseBranch = 'develop', opts = {}) {
    const exec = opts.execFn || execFilePromise;
    try {
        await exec('git', ['checkout', baseBranch], { cwd: repoRoot, timeout: GIT_TIMEOUT });
        await exec('git', ['branch', '-D', branchName], { cwd: repoRoot, timeout: GIT_TIMEOUT });
    } catch {
        // Best effort
    }
}

// ─── Helpers ──────────────────────────────────────────────────────

function gitlabApi(method, apiPath, data, { token, base_url }) {
    const parsed = new URL(base_url);
    const isHttps = parsed.protocol === 'https:';
    const transport = isHttps ? https : http;

    const body = data ? JSON.stringify(data) : null;
    const options = {
        hostname: parsed.hostname,
        port: parsed.port || (isHttps ? 443 : 80),
        path: apiPath,
        method,
        headers: {
            'PRIVATE-TOKEN': token,
            'Content-Type': 'application/json',
        },
    };
    if (body) options.headers['Content-Length'] = Buffer.byteLength(body);

    return new Promise((resolve, reject) => {
        const req = transport.request(options, (res) => {
            const chunks = [];
            res.on('data', chunk => chunks.push(chunk));
            res.on('end', () => {
                const raw = Buffer.concat(chunks).toString();
                if (res.statusCode >= 400) {
                    return reject(new Error(`GitLab API ${res.statusCode}: ${raw.slice(0, 500)}`));
                }
                try {
                    resolve(JSON.parse(raw));
                } catch {
                    reject(new Error(`Invalid JSON: ${raw.slice(0, 200)}`));
                }
            });
            res.on('error', reject);
        });
        req.on('error', reject);
        req.setTimeout(API_TIMEOUT, () => req.destroy(new Error('Request timeout')));
        if (body) req.write(body);
        req.end();
    });
}

function execFilePromise(cmd, args, opts) {
    return new Promise((resolve, reject) => {
        execFile(cmd, args, { ...opts, maxBuffer: 1024 * 1024 }, (err, stdout) => {
            if (err) return reject(err);
            resolve(stdout);
        });
    });
}

module.exports = {
    generateBranchName,
    createBranchAndCommit,
    buildCommitMessage,
    runValidation,
    createMergeRequest,
    buildMrDescription,
    cleanup,
};
