#!/usr/bin/env bash
# scripts/build.sh — ClawMark Build Script
#
# Builds the extension and dashboard for a specific environment.
#
# Usage:
#   ./scripts/build.sh test          # Build for test environment
#   ./scripts/build.sh production    # Build for production environment
#   ./scripts/build.sh               # Defaults to test
#
# What it does:
#   1. Generates extension/config.js with environment-specific values
#   2. Builds dashboard via Vite with the correct .env file
#   3. Packages extension into a zip for distribution

set -euo pipefail

ENV="${1:-test}"

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

log()  { echo "▶ $*"; }
info() { echo "  $*"; }
err()  { echo "✗ $*" >&2; exit 1; }

# ── Environment config ────────────────────────────────────────────────────────

case "$ENV" in
  test)
    SERVER_URL="https://jessie.coco.site/clawmark"
    DASHBOARD_URL="https://jessie.coco.site/clawmark-dashboard/"
    ;;
  production)
    SERVER_URL="https://api.coco.xyz/clawmark"
    DASHBOARD_URL="https://labs.coco.xyz/clawmark/dash/"
    ;;
  *)
    err "Unknown environment: $ENV (use 'test' or 'production')"
    ;;
esac

VERSION=$(jq -r '.version' package.json)
log "Building ClawMark v${VERSION} for ${ENV}"
info "Server:    $SERVER_URL"
info "Dashboard: $DASHBOARD_URL"

# ── Generate extension config.js ──────────────────────────────────────────────

log "Generating extension/config.js..."
cat > extension/config.js << CONFIGEOF
/**
 * ClawMark Extension — Build Configuration
 *
 * Auto-generated by scripts/build.sh — do not edit manually.
 * Environment: ${ENV}
 * Built: $(date -u +%Y-%m-%dT%H:%M:%SZ)
 */

'use strict';

const ClawMarkConfig = {
    DEFAULT_SERVER: '${SERVER_URL}',
    DASHBOARD_URL: '${DASHBOARD_URL}',
    ENV: '${ENV}',
};

if (typeof Object.freeze === 'function') Object.freeze(ClawMarkConfig);
CONFIGEOF

# ── Build dashboard ───────────────────────────────────────────────────────────

log "Building dashboard (mode: ${ENV})..."
cd dashboard
npm run build -- --mode "$ENV"
cd "$REPO_ROOT"
info "Dashboard built → dashboard/dist/"

# ── Package extension zip ─────────────────────────────────────────────────────

BUILD_DIR=$(mktemp -d)
ZIP_NAME="clawmark-v${VERSION}-${ENV}.zip"
ZIP_PATH="${REPO_ROOT}/${ZIP_NAME}"

log "Packaging extension..."
cp -r extension/* "$BUILD_DIR/"

# Remove dev files
rm -f "$BUILD_DIR/.gitignore" "$BUILD_DIR/.DS_Store"

cd "$BUILD_DIR"
zip -r "$ZIP_PATH" . -x "*.DS_Store" > /dev/null
cd "$REPO_ROOT"
rm -rf "$BUILD_DIR"

info "Extension zip → ${ZIP_NAME} ($(du -h "$ZIP_PATH" | cut -f1))"

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
log "✅ Build complete — ${ENV}"
info "Extension: ${ZIP_NAME}"
info "Dashboard: dashboard/dist/"
info ""
info "To deploy dashboard (test):  cp -r dashboard/dist/* /path/to/clawmark-dashboard/"
info "To deploy dashboard (prod):  copy dashboard/dist/* to labs.coco.xyz/clawmark/dash/"
